DROP SEQUENCE QNA_NO_SEQ;

DROP SEQUENCE RECRUIT_BOARD_SEQ ;

DROP SEQUENCE CHANNEL_CATEGORY_SEQ;

DROP SEQUENCE APPLY_EDITOR_SEQ;

DROP SEQUENCE VIDEO_LINKS_SEQ;

DROP SEQUENCE EDIT_TOOLS_NO_SEQ;

DROP SEQUENCE EDIT_TOOLS_RECRUIT_SEQ;

DROP TABLE EDIT_TOOLS_LIST CASCADE CONSTRAINT;

DROP TABLE VIDEO_LINKS CASCADE CONSTRAINT;

DROP TABLE APPLY_EDITOR CASCADE CONSTRAINT;

DROP TABLE CHANNEL_CATEGORY CASCADE CONSTRAINT;

DROP TABLE RECRUIT_BOARD CASCADE CONSTRAINT;

DROP TABLE PORTFOLIO CASCADE CONSTRAINT;

DROP TABLE QNA CASCADE CONSTRAINT;

DROP TABLE USER_EDITOR CASCADE CONSTRAINT;

DROP TABLE USER_YOUTUBER CASCADE CONSTRAINT;

DROP TABLE RED_CARDED_USER CASCADE CONSTRAINT;

DROP TABLE USER_INFO CASCADE CONSTRAINT;

DROP TABLE EDIT_TOOLS_RECRUIT CASCADE CONSTRAINT;


CREATE TABLE USER_INFO (
	EMAIL 				VARCHAR2(40) 						CONSTRAINT USER_INFO_EMAIL_PK 				PRIMARY KEY
, 	PASSWORD 		VARCHAR2(300)					CONSTRAINT USER_INFO_PASSWORD_NN 		NOT NULL
, 	NAME 			VARCHAR2(15) 						CONSTRAINT USER_INFO_NAME_NN 			NOT NULL
, 	NICKNAME 		VARCHAR2(30) 						CONSTRAINT USER_INFO_NICKNAME_NN 		NOT NULL
, 	PHONE_NUMBER 	VARCHAR2(150) 						CONSTRAINT USER_INFO_PHONE_NUMBER_NN 	NOT NULL
, 	ADDRESS 		VARCHAR2(150) 						CONSTRAINT USER_INFO_ADDRESS_NN 		NOT NULL
, 	DETAIL_ADDR 	VARCHAR2(150) 						CONSTRAINT USER_INFO_DETAIL_ADDR_NN 	NOT NULL
, 	USER_TYPE 		VARCHAR2(9) 						CONSTRAINT USER_INFO_USER_TYPE_NN 		NOT NULL
, 	GENDER 			VARCHAR2(3) 						CONSTRAINT USER_INFO_GENDER_NN 			NOT NULL
, 	BIRTH_DATE 		DATE 								CONSTRAINT USER_INFO_DATE_NN 			NOT NULL
, 	REGISTER_DATE  	DATE 			DEFAULT SYSDATE 	CONSTRAINT USER_INFO_REGISTER_DATE_NN 	NOT NULL
, 	PROFILE_PHOTO 	VARCHAR2(100) 	DEFAULT ' ' 			CONSTRAINT USER_INFO_PROFILE_PHOTO_NN 	NOT NULL
, 	CONSTRAINT 		USER_INFO_NICKNAME_UQ 		UNIQUE (NICKNAME)
, 	CONSTRAINT 		USER_INFO_USER_TYPE_CK 		CHECK (USER_TYPE IN ('유튜버', '편집자'))
, 	CONSTRAINT 		USER_INFO_GENDER_CK 		CHECK (GENDER IN ('남', '여'))
);

CREATE TABLE QNA (
	QNA_NO 			NUMBER(7) 							CONSTRAINT QNA_NO_PK 		PRIMARY KEY
, 	EMAIL   	    VARCHAR2(40) 						CONSTRAINT QNA_EMAIL_NN 	NOT NULL
, 	QUESTION 		VARCHAR2(1000) 						CONSTRAINT QNA_QUESTION_NN 	NOT NULL
, 	ANSWER 			VARCHAR2(1000) 		DEFAULT ' ' 		CONSTRAINT QNA_ANSWER_NN 	NOT NULL
,   POST_DATE       DATE                DEFAULT SYSDATE     CONSTRAINT QNA_POST_DATE_NN NOT NULL
, 	CONSTRAINT 		QNA_EMAIL_FK 	FOREIGN KEY (EMAIL) 	REFERENCES USER_INFO (EMAIL) ON DELETE CASCADE
);

CREATE TABLE USER_YOUTUBER (
	YOUTUBER_EMAIL 	VARCHAR2(40) 	CONSTRAINT USER_YOUTUBER_EMAIL_FK REFERENCES USER_INFO (EMAIL) ON DELETE CASCADE
, 	CHANNEL_ID 		VARCHAR2(40) 	CONSTRAINT USER_YOUTUBER_CHANNEL_ID_NN NOT NULL
,   SUBSCRIBE       NUMBER(10)       DEFAULT 0 CONSTRAINT USER_YOUTUBER_SUBSCRIBE_NN NOT NULL
,   VIDEO_COUNT     NUMBER(10)       DEFAULT 0 CONSTRAINT USER_YOUTUBER_VIDEO_COUNT_NN NOT NULL
,   VIEW_COUNT      NUMBER         DEFAULT 0 CONSTRAINT USER_YOUTUBER_VIEW_COUNT_NN NOT NULL
,   CHANNEL_NAME    VARCHAR2(100)   DEFAULT ' ' CONSTRAINT USER_YOUTUBER_NAME_NN NOT NULL
,   CHANNEL_PHOTO   VARCHAR2(300)               CONSTRAINT USER_YOUTUBER_PHOTO_NN NOT NULL
, 	CONSTRAINT 		USER_YOUTUBER_EMAIL_PK 			PRIMARY KEY (YOUTUBER_EMAIL)
,	CONSTRAINT 		USER_YOUTUBER_CHANNEL_ID_UQ 	UNIQUE (CHANNEL_ID)
);


CREATE TABLE USER_EDITOR (
 	EDITOR_EMAIL 		VARCHAR2(40) 								CONSTRAINT USER_EDITOR_EMAIL_FK REFERENCES USER_INFO(EMAIL) ON DELETE CASCADE
, 	IS_UPLOADED 	VARCHAR2(5) 				DEFAULT 'FALSE' CONSTRAINT USER_EDITOR_IS_UPLOADED_NN NOT NULL
, 	CONSTRAINT 		USER_EDITOR_EMAIL_PK 			PRIMARY KEY (EDITOR_EMAIL)
, 	CONSTRAINT 		USER_EDITOR_IS_UPLOADED_CK 	CHECK(IS_UPLOADED IN('TRUE','FALSE'))
);


CREATE TABLE RECRUIT_BOARD (
 	RECRUIT_NO 			NUMBER(7) 								CONSTRAINT RECRUIT_BOARD_NO_PK 				PRIMARY KEY
, 	YOUTUBER_EMAIL 		VARCHAR2(40) 							CONSTRAINT RECRUIT_BOARD_EMAIL_FK 	REFERENCES USER_YOUTUBER (YOUTUBER_EMAIL) ON DELETE CASCADE
, 	RECRUIT_TITLE 		VARCHAR2(100) 	DEFAULT ' ' 				CONSTRAINT RECRUIT_TITLE_NN 				NOT NULL
, 	DUTY 				VARCHAR2(300) 	DEFAULT ' ' 				CONSTRAINT RECRUIT_DUTY_NN 					NOT NULL
, 	WORKLOAD 			VARCHAR2(300) 	DEFAULT ' ' 				CONSTRAINT RECRUIT_WORKLOAD_NN 				NOT NULL
, 	REQUIREMENT 		VARCHAR2(1000) 	DEFAULT ' ' 				CONSTRAINT RECRUIT_REQUIREMENT_NN			NOT NULL
, 	SALARY_DETAIL 		VARCHAR2(300) 	DEFAULT '내용 없음' 	CONSTRAINT RECRUIT_SAL_DETAIL_NN 			NOT NULL
, 	PREFERENCE 			VARCHAR2(300) 	DEFAULT ' ' 				CONSTRAINT RECRUIT_PREFERENCE_NN 			NOT NULL
, 	ENVIRONMENT 		VARCHAR2(300) 	DEFAULT ' ' 				CONSTRAINT RECRUIT_ENVIRONMENT_NN 			NOT NULL
, 	WELFARE 			VARCHAR2(500) 	DEFAULT ' ' 				CONSTRAINT RECRUIT_WELFARE_NN 				NOT NULL
, 	RECRUIT_DETAIL 		VARCHAR2(3000) 	DEFAULT ' ' 				CONSTRAINT RECRUIT_DETAIL_NN 				NOT NULL
, 	SALARY 				VARCHAR2(30) 	DEFAULT ' ' 				CONSTRAINT RECRUIT_SALARY_NN 				NOT NULL
, 	DEADLINE 			DATE 			DEFAULT SYSDATE 		CONSTRAINT RECRUIT_DEADLINE_NN 				NOT NULL
,   ORIGINAL_LINK       VARCHAR2(300)   DEFAULT ' '             CONSTRAINT RECRUIT_ORIGINAL_LINK_NN         NOT NULL
, 	POST_DATE 		DATE 		DEFAULT SYSDATE 			CONSTRAINT RECRUIT_POST_DATE_NN 		NOT NULL
); 

CREATE TABLE EDIT_TOOLS_RECRUIT (
 	EDIT_TOOLS_NO 	NUMBER(7) 				CONSTRAINT RECRUIT_EDIT_TOOLS_NO_PK 	PRIMARY KEY
, 	RECRUIT_NO 		NUMBER(7) 				CONSTRAINT EDIT_TOOLS_RECRUIT_NO_NN 			NOT NULL
, 	EDIT_TOOL 		VARCHAR2(30) 				CONSTRAINT RECRUIT_EDIT_TOOL_NN 		NOT NULL
, 	CONSTRAINT 	TOOLS_RECRUIT_RECRUIT_NO_FK 			FOREIGN KEY (RECRUIT_NO) REFERENCES RECRUIT_BOARD (RECRUIT_NO) ON DELETE CASCADE
, 	CONSTRAINT 	TOOLS_RECRUIT_EDIT_TOOL_CK    CHECK (EDIT_TOOL IN('프리미어프로', '애프터이펙트', '베가스', '파이널컷', '파워디렉터', '포토샵', '일러스트레이터', '마야', '블렌더', '기타'))
);

CREATE TABLE CHANNEL_CATEGORY (
	CATEGORY_NO 	NUMBER(7) 						CONSTRAINT CHANNEL_CATEGORY_NO_PK 	PRIMARY KEY
,	RECRUIT_NO 		NUMBER(7) 						CONSTRAINT CATEGORY_RECRUIT_NO_FK 	REFERENCES RECRUIT_BOARD(RECRUIT_NO) ON DELETE CASCADE
,	CATEGORY 		VARCHAR2(30)	DEFAULT '기타' 	CONSTRAINT CATEGORY_NN 				NOT NULL
,	CONSTRAINT 		CATEGORY_CK 	CHECK(CATEGORY IN('먹방','게임','일상','요리','음악','영화','스포츠','학습','소통','자동차','IT','이슈','동물','기타'))
);


CREATE TABLE PORTFOLIO (
	EDITOR_EMAIL 			VARCHAR2(40) 					CONSTRAINT 	PORTFOLIO_EMAIL_FK 			REFERENCES 	USER_EDITOR (EDITOR_EMAIL) ON DELETE CASCADE
,	IS_PUBLIC 			VARCHAR2(5) 						CONSTRAINT 	PORTFOLIO_IS_PUBLIC_NN 		NOT NULL
,	WORKABLE_LOCATION 	VARCHAR2(100) 	DEFAULT ' ' 		CONSTRAINT PORTFOLIO_LOCATION_NN 		NOT NULL
,	YOUTUBE_CAREER 		VARCHAR2(1000) 	DEFAULT ' ' 		CONSTRAINT PORTFOLIO_Y_CAREER_NN			NOT NULL
,	OTHER_CAREER 		VARCHAR2(1000) 	DEFAULT ' ' 		CONSTRAINT PORTFOLIO_O_CAREER_NN			NOT NULL
,	MESSAGE 			VARCHAR2(3000) 	DEFAULT ' ' 		CONSTRAINT PORTFOLIO_MESSAGE_NN 		NOT NULL
,	PORTFOLIO_TITLE 	VARCHAR2(100) 	DEFAULT ' '		CONSTRAINT PORTFOLIO_TITLE_NN 			NOT NULL
,	POST_DATE 			DATE 			DEFAULT SYSDATE CONSTRAINT PORTFOLIO_POST_DATE_NN		NOT NULL
,   DESIRED_SALARY      VARCHAR2(300)      DEFAULT 0       CONSTRAINT PORTFOLIO_DESIRED_SAL_NN     NOT NULL
,   DESIRED_WORK_TYPE   VARCHAR2(100)   DEFAULT ' '     CONSTRAINT PORTFOLIO_DESIRED_WORK_TYPE_NN NOT NULL
,   MESSAGE_TO_YOUTUBER VARCHAR2(3000)  DEFAULT ' '     CONSTRAINT PORTFOLIO_MESSAGE_TO_YTB_NN  NOT NULL
,	CONSTRAINT 	PORTFOLIO_EMAIL_PK 				PRIMARY KEY (EDITOR_EMAIL)
,	CONSTRAINT 	PORTFOLIO_IS_PUBLIC_CK 			CHECK(IS_PUBLIC IN('TRUE','FALSE'))
);


CREATE TABLE APPLY_EDITOR (
 	APPLY_NO 		NUMBER(7) 					CONSTRAINT APPLY_EDITOR_APPLY_NO_PK 		PRIMARY KEY
, 	RECRUIT_NO 		NUMBER(7) 					CONSTRAINT APPLY_EDITOR_RECRUIT_NO_NN 		NOT NULL
, 	EDITOR_EMAIL 		VARCHAR2(40) 				CONSTRAINT APPLY_EDITOR_ID_NN 				NOT NULL
, 	EDITED_LINK 	VARCHAR2(100) 	DEFAULT ' '		CONSTRAINT APPLY_EDITOR_EDITED_LINK_NN 		NOT NULL
, 	EDITOR_MEMO 	VARCHAR2(1000) 	DEFAULT ' ' 	CONSTRAINT APPLY_EDITOR_EDITOR_MEMO_NN 		NOT NULL
, 	YOUTUBER_MEMO 	VARCHAR2(1000) 	DEFAULT ' ' 	CONSTRAINT APPLY_EDITOR_YOUTUBER_MEMO_NN 	NOT NULL
, 	CONSTRAINT 	APPLY_EDITOR_RECRUIT_NO_FK 		FOREIGN KEY (RECRUIT_NO) 	REFERENCES RECRUIT_BOARD (RECRUIT_NO) ON DELETE CASCADE
, 	CONSTRAINT 	APPLY_EDITOR_EMAIL_FK 				FOREIGN KEY (EDITOR_EMAIL) 	REFERENCES USER_EDITOR (EDITOR_EMAIL) ON DELETE CASCADE
);


CREATE TABLE VIDEO_LINKS (
 	VIDEO_NO 	VARCHAR2(7) 		CONSTRAINT VIDEO_LINKS_VIDEO_NO_PK 		PRIMARY KEY
, 	EDITOR_EMAIL 	VARCHAR2(40) 		CONSTRAINT VIDEO_LINKS_EMAIL_NN 			NOT NULL
, 	VIDEO_LINK 	VARCHAR2(500) 		CONSTRAINT VIDEO_LINKS_VIDEO_LINK_NN 	NOT NULL
, 	PRIORITY 	NUMBER(2) 			CONSTRAINT VIDEO_LINKS_PRIORITY_NN 		NOT NULL
, 	CONSTRAINT 	VIDEO_LINKS_ID_FK 	FOREIGN KEY (EDITOR_EMAIL) REFERENCES PORTFOLIO (EDITOR_EMAIL) ON DELETE CASCADE
);


CREATE TABLE EDIT_TOOLS_LIST (
 	EDIT_TOOLS_NO 	NUMBER(7) 				CONSTRAINT TOOLS_LIST_EDIT_TOOLS_NO_PK 	PRIMARY KEY
, 	EDITOR_EMAIL 		VARCHAR2(40) 				CONSTRAINT TOOLS_LIST_EMAIL_NN 			NOT NULL
, 	EDIT_TOOL 		VARCHAR2(30) 				CONSTRAINT TOOLS_LIST_EDIT_TOOL_NN 		NOT NULL
, 	CONSTRAINT 	EDIT_TOOLS_LIST_EMAIL_FK 			FOREIGN KEY (EDITOR_EMAIL) REFERENCES PORTFOLIO (EDITOR_EMAIL) ON DELETE CASCADE
, 	CONSTRAINT 	EDIT_TOOLS_LIST_EDIT_TOOL_CK    CHECK (EDIT_TOOL IN('프리미어프로', '애프터이펙트', '베가스', '파이널컷', '파워디렉터', '포토샵', '일러스트레이터', '마야', '블렌더', '기타'))
);

CREATE SEQUENCE QNA_NO_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE RECRUIT_BOARD_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE CHANNEL_CATEGORY_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 100000
    NOCYCLE
    NOCACHE;
    
    
CREATE SEQUENCE APPLY_EDITOR_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE VIDEO_LINKS_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE EDIT_TOOLS_NO_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE EDIT_TOOLS_RECRUIT_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    NOCYCLE
    NOCACHE;
    